### ISSUE TITLE
is this beeing updated ?

### ISSUE THREAD

**Issue by DennyFiguerres** [Tiberriver256/Swashbuckle.AspNetCore.Community.OData#104]
### Describe the feature

is anyone using this ? is it beeing maintained ?

**Comment by Tiberriver256** [comment]
Hi @DennyFiguerres, I do plan on occasionally making changes to this on occasion and am happy to accept any PRs.

That being said, if you're looking for something enterprise-ready I would probably fork this and maintain it internally. There's a relatively small amount of code here and it's likely I'm not going to be near as active/responsive as you need.

**Comment by DennyFiguerres** [comment]
> Hi @DennyFiguerres, I do plan on occasionally making changes to this on occasion and am happy to accept any PRs.
> 
> That being said, if you're looking for something enterprise-ready I would probably fork this and maintain it internally. There's a relatively small amount of code here and it's likely I'm not going to be near as active/responsive as you need.

actually i am trying to see if i can get restier and swagger to work and at one point you wrote on the restier side that you had it working and then you deleted the fork that worked.... you wrote that you would show how you did it but i have not been able to find out how.....   if you can do something to help thatn would be great!   i really want to get swagger working as it sure helps!
i got the source from the repo but i am stuck on the foreach (var route in this.odataOptions.RouteComponents)
which is not in the older package that restier uses right now.....
if you can put up some code that gets it to work with resiter i will take that and work with it ..... and work with restier folks on getting it to run with the current package versions ......   

thanks!

**Comment by Tiberriver256** [comment]
Yeah, I got over-ambitious on cleaning up my personal repos and deleted it. The trick is figuring out how to pull out the EdmModel. I'm not sure when I'll get around to figuring that out again.

A note, though... this is only required if you want to serve the swagger live from the same endpoint. There are command line utilities [like this one](https://oasis-tcs.github.io/odata-openapi/lib/) that convert the results of the `/$metadata` endpoint into Swagger that might be easier to use.

**Comment by DennyFiguerres** [comment]
Hmm..... darn!
